backend: {name: git-gateway, branch: main}
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
collections: [{name: pages, label: Pages, files: [{name: home, label: "Home Page", file: index.html, format: frontmatter, fields: [{label: "Page HTML", name: body, widget: code, default_language: html, allow_language_selection: false, output_code_only: true}]}, {name: about, label: "About Page", file: about.html, format: frontmatter, fields: [{label: "Page HTML", name: body, widget: code, default_language: html, allow_language_selection: false, output_code_only: true}]}]}]
